version: '3.2'
services:
    fakegree:
      image: fakegree
      build: fakegree
      restart: always
      volumes:
      - ./fakegree:/fakegree
      environment:
        IP: 192.168.0.69  # change this to a free IP in the HVAC's subnet
        TLS: False # Change this if you have a new unit that uses TLS
        PORT: 1812 # leave this
        HOSTNAME: dis.gree.com # change to eu.dis.gree.com for europe
      networks:
        dirty:
          ipv4_address: 192.168.0.69 # must match the IP above
networks:
  dirty:
    driver: macvlan
    name: dirty
    driver_opts:
      parent: vlan88
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24  # change this to the HVAC's subnet
          gateway: 192.168.0.11   # change this to the HVAC's subnet's gateway

